#!/bin/bash

if [ $# -lt 3 ]
then
    echo "Brak parametrow [katalog aktualne] [katalog zakonczone] [projekt]" >> /home/kasia/$3_backup.log
else
    ACTDIR=$1
    if [ ${ACTDIR: -1} != "/" ]
    then
        ACTDIR=$1/
    fi

    ARCHDIR=$2
    if [ ${ARCHDIR: -1} != "/" ]
    then
        ARCHDIR=$2/
    fi

    PROJ=$3

    if [ -d "${ACTDIR}${PROJ}" ]
    then
        if [ -d "${ARCHDIR}" ]
        then
            find ${ACTDIR}${PROJ} -type f -name *.bak -exec rm {} +
            find ${ACTDIR}${PROJ} -type f -name *.tmp -exec rm {} +
            mv ${ACTDIR}${PROJ} ${ARCHDIR}
            find ${ARCHDIR}${PROJ} -exec chown pmanager:biuro {} +
            find ${ARCHDIR}${PROJ} -type f -exec chmod 0664 {} +
            find ${ARCHDIR}${PROJ} -type d -exec chmod 0775 {} +
            DATA=`date +%Y%m%d`
            echo "Trwa generowanie archiwum..." >> /home/kasia/${PROJ}_backup.log
            7z a -t7z /home/kasia/kopia_zakonczone/${PROJ}_$DATA.7z ${ARCHDIR}${PROJ} -mx9 >> /home/kasia/${PROJ}_backup.log
            find /home/kasia/kopia_zakonczone/${PROJ}_$DATA.7z -exec chown kasia:archiwum {} +
            echo "Generowanie archiwum zakonczone" >> /home/kasia/${PROJ}_backup.log
            echo "backup-$DATA" >> /home/kasia/${PROJ}_backup.log
            cat archivealert.txt > /tmp/email.txt
            echo ${PROJ} >> /tmp/email.txt
            ssmtp tomasz.tkaczyk@unipromax.pl < /tmp/email.txt
        else
            echo "Katalog ${ARCHDIR} nie istnieje."
        fi
    else
        echo "Katalog ${ACTDIR}${PROJ} nie istnieje."
    fi
fi

