#!/bin/bash

if [ $# -lt 3 ]
then
    echo "Brak parametrow"
else
    ARCHDIR=$1
    if [ ${ARCHDIR: -1} != "/" ]
    then
        ARCHDIR=$1/
    fi

    ACTDIR=$2
    if [ ${ACTDIR: -1} != "/" ]
    then
        ACTDIR=$2/
    fi

    PROJ=$3

    mv ${ARCHDIR}${PROJ} ${ACTDIR}

    ${ACTDIR}/folderprivilege ${PROJ}
fi
